spring:
  application:
    name: document-service
  datasource:
    url: jdbc:postgresql://localhost:5432/itq_db
    username: itq_user
    password: itq_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    web:
      pageable:
        default-page-size: 30
        page-parameter: page
        size-parameter: size
        max-page-size: 100

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: ${PORT:8080}

logging:
  level:
    liquibase: DEBUG
    org.hibernate.orm.jdbc.bind: trace
